# HDC JLink API Configuration
# แก้ไขค่าให้ตรงกับ environment ที่ใช้งาน

# App ID สำหรับเรียก HDC JLink API
hdc.app_id=b2bcdda1-530e-489e-9985-ce5e572bee20

# Base URL ของ HDC JLink API
hdc.base_url=https://poc.moph.go.th/jlink/api
