#SSO Properties - Provider Credentials
#Do NOT commit this file to version control

# ThaID (BORA)
thaid.client_id=dHNvZU11c0NDTXhaUEVuV0hRSExwMnhWRW5yaTFHRDU
thaid.client_secret=YjlEUlpsYW5VZDdrN2FidWxWVEtOMEN4eUp1UEtjTm5QbVg5Rm9ieQ
thaid.redirect_uri=https://indev.moph.go.th/auth/realms/jhcis/broker/thaiid/endpoint
thaid.auth_url=https://imauth.bora.dopa.go.th/api/v2/oauth2/auth/
thaid.token_url=https://imauth.bora.dopa.go.th/api/v2/oauth2/token/
thaid.introspect_url=https://imauth.bora.dopa.go.th/api/v2/oauth2/introspect/

# Health ID (moph.id.th)
healthid.client_id=9c7a8150-e83d-4f6a-b01f-01b1f78d3d75
healthid.client_secret=jbf8XsFaYH02zIDkK5d0v50KaypatfQHHKiVhZt2
healthid.redirect_uri=https://indev.moph.go.th/auth/realms/jhcis/broker/ProviderID/endpoint
healthid.auth_url=https://moph.id.th/oauth/redirect
healthid.token_url=https://moph.id.th/api/v1/token

# Provider ID (provider.id.th)
providerid.client_id=57c20f8f-bfd0-4e3d-b4b8-6c98cfb3d8e8
providerid.secret_key=D5FE4DE2CE2EE6D5DD4C59BBADFD5
providerid.token_url=https://provider.id.th/api/v1/services/token
providerid.profile_url=https://provider.id.th/api/v1/services/profile

# MyMoph (auth.moph.go.th)
mymoph.client_id=ifdqmGtertIqHqxSgInJ
mymoph.client_secret=hAFtMMk5tUPE
mymoph.redirect_uri=https://indev.moph.go.th/auth/realms/jhcis/broker/my-moph/endpoint
mymoph.auth_url=https://auth.moph.go.th/v1/oauth2/auth
mymoph.token_url=https://auth.moph.go.th/v1/oauth2/token
mymoph.profile_url=https://members.moph.go.th/api/v1/info