/*
 * JDialog_Rep_bmi_waist_fsb.java
 *
 * Created on 6 กุมภาพันธ์ 2551, 13:40 น.
 */

package pcu;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import pcu.PersistentClass.CheckUpdate;
import pcu.PersistentClass.Office;
import pcu.PersistentClass.UserInfo;
//import javax.swing.DefaultComboBoxModel;
import pcu.PersistentClass.ComboBox;

/**
 *
 * @author  sumrit
 * chariya แก้ไขเพิ่มเติมให้เลือกหน่วยงาน 30 มีค.53
 */
public class JDialog_Rep_bmi_waist_fsb extends javax.swing.JDialog {
    private Office office;
    private String sDate,eDate,pDate,pcucode,offAddress,pcu;
    private ComboBox cb_Office;
    /**
     * Creates new form JDialog_Rep_bmi_waist_fsb
     */
    public JDialog_Rep_bmi_waist_fsb(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pcucode = UserInfo.pcucode;
        initComponents();
        new CheckUpdate(getContentPane().getComponents());
        office = new Office(); 
        
        cb_Office = new ComboBox("SELECT CONCAT(hosname,'(',CONVERT(hoscode USING utf8),')' ),offid FROM chospital,office WHERE office.offid<>'0000x' AND office.offid=chospital.hoscode ");
        cbOffice.setModel(new javax.swing.DefaultComboBoxModel(cb_Office.getVname()));
        cbOffice.setSelectedIndex(cb_Office.indexOf(UserInfo.pcucode));
        offAddress = setupPcu.getOffaddress(cbOffice.getSelectedIndex(),cb_Office.getCode(cbOffice));
        jXDateStart.setDate(office.getDaterepStart());
        jXDateEnd.setDate(office.getDaterepEnd());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btg_age = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbDateStart = new javax.swing.JLabel();
        jXDateStart = new pcu.swingx.JXdate();
        lbDateEnd = new javax.swing.JLabel();
        jXDateEnd = new pcu.swingx.JXdate();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btWaist = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cbOffice = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lbDateStart.setFont(new java.awt.Font("Tahoma", 0, 12));
        lbDateStart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDateStart.setText("ข้อมูลรายงาน ตั้งแต่วันที่:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
        jPanel1.add(lbDateStart, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 106;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
        jPanel1.add(jXDateStart, gridBagConstraints);

        lbDateEnd.setFont(new java.awt.Font("Tahoma", 0, 12));
        lbDateEnd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDateEnd.setText("ถึงวันที่:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(lbDateEnd, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 105;
        jPanel1.add(jXDateEnd, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(289, 48));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("อายุสำหรับรายงานการวัดรอบเอว");

        btg_age.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("15 ปีขึ้นไป");
        jRadioButton1.setActionCommand("15");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btg_age.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jRadioButton2.setText("35 ปีขึ้นไป");
        jRadioButton2.setActionCommand("35");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(289, 48));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton3.setText("จำนวนประชากร...และผลการตรวจระดับน้ำตาลในเลือด(FSB)");
        jButton3.setActionCommand("rptfsbover35y");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jButton3, gridBagConstraints);

        btWaist.setFont(new java.awt.Font("Tahoma", 0, 12));
        btWaist.setText("จำนวนประชากร...และผลการตรวจวัดรอบเอว");
        btWaist.setActionCommand("rptwaistover35y");
        btWaist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWaistActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(btWaist, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton2.setText("จำนวนประชากร...และผลการตรวจวัดดัชนีมวลกาย(BMI)");
        jButton2.setActionCommand("rptbmiover35y");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jButton2, gridBagConstraints);

        jPanel4.setLayout(null);

        cbOffice.setFont(new java.awt.Font("Tahoma", 0, 12));
        jPanel4.add(cbOffice);
        cbOffice.setBounds(10, 20, 390, 30);

        jLabel2.setText("ข้อมูลหน่วยงาน");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 0, 190, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btWaistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWaistActionPerformed
    print(evt);  
}//GEN-LAST:event_btWaistActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    print(evt);    
}//GEN-LAST:event_jButton3ActionPerformed
    
    private void print(java.awt.event.ActionEvent evt){
        sDate = jXDateStart.getDate();        
        eDate = jXDateEnd.getDate();
        pDate = new java.sql.Date(new Date().getTime()).toString();
        int age = Integer.parseInt(btg_age.getSelection().getActionCommand());
        if(cbOffice.getSelectedIndex() < 1){
            pcucode = "";
          }else {
           pcu = cb_Office.getCode(cbOffice);
           pcucode = " AND v.pcucode = " + pcu ;
          }
        Map pm = new HashMap();
        pm.put("sdate",sDate);
        pm.put("edate",eDate);
        pm.put("pdate",pDate);
        pm.put("pcucode",pcucode);
        pm.put("age",age);
        pm.put("SUBREPORT_DIR", "./reports/");
        setVisible(false);
        new RunReport(this, pm,evt.getActionCommand()+".jasper");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserInfo.pcucode = "08727";
                new JDialog_Rep_bmi_waist_fsb(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btWaist;
    private javax.swing.ButtonGroup btg_age;
    private javax.swing.JComboBox cbOffice;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private pcu.swingx.JXdate jXDateEnd;
    private pcu.swingx.JXdate jXDateStart;
    private javax.swing.JLabel lbDateEnd;
    private javax.swing.JLabel lbDateStart;
    // End of variables declaration//GEN-END:variables

   
    
}
