/*
 * QueryDiag.java
 *
 * Created on 11 มกราคม 2553, 18:34 น.
 */

package pcu;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pcu.PersistentClass.ComboBox;
import pcu.PersistentClass.DBPersistentObject;
import pcu.PersistentClass.Office;
import pcu.PersistentClass.UserInfo;
/**
 *
 * @author  sumrit
 */
public class QueryDiag extends javax.swing.JDialog {
    private Office of;
    private String startdate,enddate,pcucode,diseasecode1 ,diseasecode2 ,diseasecode3 ,diseasecode4 ,diseasecode5;
    private DBPersistentObject db;
    //private ResultSet rs;
    private String reportdir = "./reports/";
    private HashMap pm;
    private String offAddress;
    private String sqlDate;
    private String sqlDisease;
    private ComboBox cb_Office;

    /** Creates new form QueryDiag */
    public QueryDiag(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        of = new Office();
        
        jXdate1.setDate(of.getDaterepStart());
        jXdate2.setDate(of.getDaterepEnd());

        //Create Office's combo box
        cb_Office = new ComboBox("SELECT CONCAT(hosname,'(',CONVERT(hoscode USING utf8),')'), offid FROM chospital, office WHERE office.offid<>'0000x' AND office.offid=chospital.hoscode ");
        cbOffice.setModel((ComboBoxModel) new DefaultComboBoxModel(cb_Office.getVname()));   

        //Show current loggin on office as default
        cbOffice.setSelectedIndex(cb_Office.indexOf(UserInfo.pcucode));
        offAddress = setupPcu.getOffid(cbOffice.getSelectedIndex(),cb_Office.getCode(cbOffice));
        
        
        setTitle("ค้นหาข้อมูลการป่วย ...");
//        jxtD1.setForeground(new java.awt.Color(155));                
        String sqlJxt = "SELECT concat(diseasecode,'-',diseasenamethai,' - ',diseasename) as diseasename,diseasecode FROM cdisease " +
                " where diseasename like '%!!!!!%' OR diseasenamethai like '%!!!!!%' OR diseasecode like '!!!!!%'";
        jxtD1.setSql(sqlJxt);
        jxtD2.setSql(sqlJxt);
        jxtD3.setSql(sqlJxt);
        jxtD4.setSql(sqlJxt);
        jxtD5.setSql(sqlJxt);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXdate1 = new pcu.swingx.JXdate();
        jXdate2 = new pcu.swingx.JXdate();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jBt_querydisease = new javax.swing.JButton();
        jBt_top10village = new javax.swing.JButton();
        jBt_queryDiseaseDrug = new javax.swing.JButton();
        jBt_top10 = new javax.swing.JButton();
        jxtD1 = new pcu.swingx.JXTextFieldDialog();
        jxtD2 = new pcu.swingx.JXTextFieldDialog();
        jxtD3 = new pcu.swingx.JXTextFieldDialog();
        jxtD4 = new pcu.swingx.JXTextFieldDialog();
        jxtD5 = new pcu.swingx.JXTextFieldDialog();
        jpOffice = new javax.swing.JPanel();
        cbOffice = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ค้นหาข้อมูลการป่วย ตามเงื่อนไขที่ระบุ (ช่วงวันที่ของการป่วย และโรคที่ป่วย)");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 670, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("1.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 30, 28));

        jXdate1.setForeground(new java.awt.Color(255, 0, 204));
        getContentPane().add(jXdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, 29));

        jXdate2.setForeground(new java.awt.Color(255, 0, 204));
        getContentPane().add(jXdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 180, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ถึงวันที่:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 90, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ระหว่างวันที่:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 29));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("2.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 30, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("3.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 30, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("4.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 30, 28));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("5.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 30, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("หรือ:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 48, 28));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("หรือ:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 48, 28));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("หรือ:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 48, 28));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("หรือ:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 48, 28));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("หรือ:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 48, 28));

        jBt_querydisease.setFont(new java.awt.Font("Tahoma", 0, 12));
        jBt_querydisease.setForeground(new java.awt.Color(0, 102, 102));
        jBt_querydisease.setText("นับครั้ง");
        jBt_querydisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_querydiseaseActionPerformed(evt);
            }
        });
        getContentPane().add(jBt_querydisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 320, 30));

        jBt_top10village.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBt_top10village.setForeground(new java.awt.Color(0, 102, 102));
        jBt_top10village.setText("10 อันดับโรคที่ป่วยสูงสุด ทั้งหมด จำแนกรายหมู่บ้าน");
        jBt_top10village.setActionCommand("10 อันดับโรคที่ป่วยสูงสุด จำแนกรายหมู่บ้าน");
        jBt_top10village.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_top10villageActionPerformed(evt);
            }
        });
        getContentPane().add(jBt_top10village, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 290, 30));

        jBt_queryDiseaseDrug.setFont(new java.awt.Font("Tahoma", 0, 12));
        jBt_queryDiseaseDrug.setForeground(new java.awt.Color(0, 102, 102));
        jBt_queryDiseaseDrug.setText("แสดงเวชภัณฑ์ที่จ่ายฯ");
        jBt_queryDiseaseDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_queryDiseaseDrugActionPerformed(evt);
            }
        });
        getContentPane().add(jBt_queryDiseaseDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 290, 30));

        jBt_top10.setFont(new java.awt.Font("Tahoma", 0, 12));
        jBt_top10.setForeground(new java.awt.Color(0, 102, 102));
        jBt_top10.setText("10 อันดับโรคที่ป่วยสูงสุด ทั้งหมด");
        jBt_top10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_top10ActionPerformed(evt);
            }
        });
        getContentPane().add(jBt_top10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 320, 30));

        jxtD1.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jxtD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 590, 28));

        jxtD2.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jxtD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 590, 28));

        jxtD3.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jxtD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 590, 28));

        jxtD4.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jxtD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 590, 28));

        jxtD5.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jxtD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 590, 28));

        jpOffice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ข้อมูลของหน่วยงาน", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        cbOffice.setFont(new java.awt.Font("Tahoma", 0, 12));
        cbOffice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOfficeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jpOfficeLayout = new javax.swing.GroupLayout(jpOffice);
        jpOffice.setLayout(jpOfficeLayout);
        jpOfficeLayout.setHorizontalGroup(
            jpOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOfficeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cbOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpOfficeLayout.setVerticalGroup(
            jpOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOfficeLayout.createSequentialGroup()
                .addComponent(cbOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 620, 60));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-697)/2, (screenSize.height-428)/2, 697, 428);
    }// </editor-fold>//GEN-END:initComponents

private void jBt_top10villageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_top10villageActionPerformed
    String pcu;
    //10 อันดับโรคป่วยสูงสุด แยกตามหมูบ้าน
    if (cbOffice.getSelectedIndex() < 1) {
        pcucode = "";
    } else {
        pcu = cb_Office.getCode(cbOffice);
        pcucode = " AND village.pcucode='" + pcu + "'";
    }

    String bDate = jXdate1.getDate();
    Date dateRepStart = new java.util.Date();
    dateRepStart.setTime(jXdate1.getDateInMillis());

    String eDate = jXdate2.getDate();
    Date dateRepEnd = new java.util.Date();
    dateRepEnd.setTime(jXdate2.getDateInMillis());
    
    sqlDate = " AND (`visit`.`visitdate` between '" + bDate + "' AND '" + eDate + "')";
    
    pm = new HashMap();
    pm.put("SUBREPORT_DIR", "./reports/");
    pm.put("p_reportOffice", offAddress);
    pm.put("p_sqlPcu", pcucode);
    pm.put("p_startDate", dateRepStart);
    pm.put("p_endDate", dateRepEnd);
    pm.put("p_sqlDate", sqlDate);
    setVisible(false);
    new RunReport(this, pm, "top10_disease_village.jasper");
    
}//GEN-LAST:event_jBt_top10villageActionPerformed

private void jBt_top10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_top10ActionPerformed
        String pcu;
    //10 อันดับโรคป่วยสูงสุด
    if (cbOffice.getSelectedIndex() < 1) {
        pcucode = "";
    } else {
        pcu = cb_Office.getCode(cbOffice);
        pcucode = " AND visit.pcucode='" + pcu + "'";
    }

    String bDate = jXdate1.getDate();
    Date dateRepStart = new java.util.Date();
    dateRepStart.setTime(jXdate1.getDateInMillis());

    String eDate = jXdate2.getDate();
    Date dateRepEnd = new java.util.Date();
    dateRepEnd.setTime(jXdate2.getDateInMillis());
    
    sqlDate = " AND (`visit`.`visitdate` between '" + bDate + "' AND '" + eDate + "')";
    
    pm = new HashMap();
    pm.put("SUBREPORT_DIR", "./reports/");
    pm.put("p_reportOffice", offAddress);
    pm.put("p_sqlPcu", pcucode);
    pm.put("p_startDate", dateRepStart);
    pm.put("p_endDate", dateRepEnd);
    pm.put("p_sqlDate", sqlDate);
    setVisible(false);
    new RunReport(this, pm, "top10_disease.jasper");
    //JOptionPane.showMessageDialog(this, "!...ขออภัย รายงานยังไม่เรียบร้อย ");
}//GEN-LAST:event_jBt_top10ActionPerformed

private void jBt_querydiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_querydiseaseActionPerformed
    String pcu;
    //นับครั้ง visit.visitno ตามโรคที่เลือก
    if (cbOffice.getSelectedIndex() < 1) {
         pcucode = "";
    } else {
        pcu = cb_Office.getCode(cbOffice);
        pcucode = " AND visit.pcucode='" + pcu + "'";
    }

    String bDate = jXdate1.getDate();
    Date dateRepStart = new java.util.Date();
    dateRepStart.setTime(jXdate1.getDateInMillis());

    String eDate = jXdate2.getDate();
    Date dateRepEnd = new java.util.Date();
    dateRepEnd.setTime(jXdate2.getDateInMillis());
    
    sqlDate = " AND (visit.visitdate between '" + bDate + "' AND '" + eDate + "')";
    
    //Query for Diseasecode
    String dCode1 = jxtD1.getText();
    String dCode2 = jxtD2.getText();
    String dCode3 = jxtD3.getText();
    String dCode4 = jxtD4.getText();
    String dCode5 = jxtD5.getText();
    sqlDisease = " AND ( cdisease.diseasecode in(";
    if(!dCode1.isEmpty()){ 
        sqlDisease += "'"+dCode1+"'";
    }
    if(!dCode2.isEmpty()){ 
        if(dCode1.isEmpty()){
            sqlDisease += "'"+dCode2+"'";
        }else{
            sqlDisease += ",'"+dCode2+"'";        
        }             
    }
    if(!dCode3.isEmpty()){ 
        if(dCode1.isEmpty()&& dCode2.isEmpty() ){
            sqlDisease += "'"+dCode3+"'";
        }else{
            sqlDisease += ",'"+dCode3+"'";        
        }             
    }
    if(!dCode4.isEmpty()){ 
        if(dCode1.isEmpty()&& dCode2.isEmpty() && dCode3.isEmpty() ){
            sqlDisease += "'"+dCode4+"'";
        }else{
            sqlDisease += ",'"+dCode4+"'";        
        }             
    }
    if(!dCode5.isEmpty()){ 
        if(dCode1.isEmpty()&& dCode2.isEmpty() && dCode3.isEmpty() && dCode4.isEmpty() ){
            sqlDisease += "'"+dCode5+"'";
        }else{
            sqlDisease += ",'"+dCode5+"'";        
        }             
    }
    
    sqlDisease += "))";
    System.out.println(sqlDisease);
    pm = new HashMap();
    pm.put("SUBREPORT_DIR", "./reports/");
    pm.put("p_reportOffice", offAddress);
    pm.put("p_startDate", dateRepStart);
    pm.put("p_endDate", dateRepEnd);
    pm.put("p_sqlDate", sqlDate);
    pm.put("p_sqlDisease", sqlDisease);
    
    if (cbOffice.getSelectedIndex() < 1) {
        JOptionPane.showMessageDialog(this, "กรุณาเลือกหน่วยงานที่ต้องการสอบถามข้อมูลก่อน ");
    }else{
        if( dCode1.isEmpty() && dCode2.isEmpty() && dCode3.isEmpty() && dCode4.isEmpty() && dCode5.isEmpty()){
            JOptionPane.showMessageDialog(this, "กรุณาเลือกโรคที่ต้องการสอบถามข้อมูลก่อน ");
            cbOffice.requestFocus();
        }else{
            setVisible(false);
            new RunReport(this, pm, "query_disease.jasper");
        }
    }
}//GEN-LAST:event_jBt_querydiseaseActionPerformed

private void jBt_queryDiseaseDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_queryDiseaseDrugActionPerformed
    String pcu;
    //นับครั้ง visit.visitno ตามโรคที่เลือก
    if (cbOffice.getSelectedIndex() < 1) {
        pcucode = "";
    } else {
        pcu = cb_Office.getCode(cbOffice);
        pcucode = " AND visit.pcucode='" + pcu + "'";
    }

    String bDate = jXdate1.getDate();
    Date dateRepStart = new java.util.Date();
    dateRepStart.setTime(jXdate1.getDateInMillis());

    String eDate = jXdate2.getDate();
    Date dateRepEnd = new java.util.Date();
    dateRepEnd.setTime(jXdate2.getDateInMillis());
    
    sqlDate = " AND (`visit`.`visitdate` between '" + bDate + "' AND '" + eDate + "')";
    
    //Query for Diseasecode
    String dCode1 = jxtD1.getText();
    String dCode2 = jxtD2.getText();
    String dCode3 = jxtD3.getText();
    String dCode4 = jxtD4.getText();
    String dCode5 = jxtD5.getText();
    //System.out.println(jxtD1.getText());
    //System.out.println(jxtD1.getItem());
    sqlDisease = " AND ( cdisease.diseasecode in(";
    if(!dCode1.isEmpty()){ 
        sqlDisease += "'"+dCode1+"'";
    }
    if(!dCode2.isEmpty()){ 
        if(dCode1.isEmpty()){
            sqlDisease += "'"+dCode2+"'";
        }else{
            sqlDisease += ",'"+dCode2+"'";        
        }             
    }
    if(!dCode3.isEmpty()){ 
        if(dCode1.isEmpty()&& dCode2.isEmpty() ){
            sqlDisease += "'"+dCode3+"'";
        }else{
            sqlDisease += ",'"+dCode3+"'";        
        }             
    }
    if(!dCode4.isEmpty()){ 
        if(dCode1.isEmpty()&& dCode2.isEmpty() && dCode3.isEmpty() ){
            sqlDisease += "'"+dCode4+"'";
        }else{
            sqlDisease += ",'"+dCode4+"'";        
        }             
    }
    if(!dCode5.isEmpty()){ 
        if(dCode1.isEmpty()&& dCode2.isEmpty() && dCode3.isEmpty() && dCode4.isEmpty() ){
            sqlDisease += "'"+dCode5+"'";
        }else{
            sqlDisease += ",'"+dCode5+"'";        
        }             
    }
    
    sqlDisease += "))";
    pm = new HashMap();
    pm.put("SUBREPORT_DIR", "./reports/");
    pm.put("p_reportOffice", offAddress);
    pm.put("p_startDate", dateRepStart);
    pm.put("p_endDate", dateRepEnd);
    pm.put("p_sqlDate", sqlDate);
    pm.put("p_sqlDisease", sqlDisease);

    //System.out.println(sqlDisease);
    if (cbOffice.getSelectedIndex() < 1) {
        JOptionPane.showMessageDialog(this, "กรุณาเลือกหน่วยงานที่ต้องการสอบถามข้อมูลก่อน ");
    }else{
        if( dCode1.isEmpty() && dCode2.isEmpty() && dCode3.isEmpty() && dCode4.isEmpty() && dCode5.isEmpty()){
            JOptionPane.showMessageDialog(this, "กรุณาเลือกโรคที่ต้องการสอบถามข้อมูลก่อน ");
            cbOffice.requestFocus();
        }else{
            setVisible(false);
            new RunReport(this, pm, "query_disease_drug.jasper");
        }
    }
}//GEN-LAST:event_jBt_queryDiseaseDrugActionPerformed

private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    JOptionPane.showMessageDialog(null, jxtD1.getText());
}//GEN-LAST:event_jLabel1MouseClicked

private void cbOfficeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOfficeItemStateChanged
if (evt.getStateChange() == 1) {
        offAddress = setupPcu.getOffaddress(cbOffice.getSelectedIndex(), cb_Office.getCode(cbOffice));

    }
}//GEN-LAST:event_cbOfficeItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QueryDiag dialog = new QueryDiag(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbOffice;
    private javax.swing.JButton jBt_queryDiseaseDrug;
    private javax.swing.JButton jBt_querydisease;
    private javax.swing.JButton jBt_top10;
    private javax.swing.JButton jBt_top10village;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private pcu.swingx.JXdate jXdate1;
    private pcu.swingx.JXdate jXdate2;
    private javax.swing.JPanel jpOffice;
    private pcu.swingx.JXTextFieldDialog jxtD1;
    private pcu.swingx.JXTextFieldDialog jxtD2;
    private pcu.swingx.JXTextFieldDialog jxtD3;
    private pcu.swingx.JXTextFieldDialog jxtD4;
    private pcu.swingx.JXTextFieldDialog jxtD5;
    // End of variables declaration//GEN-END:variables
//    btdel.setFont(new java.awt.Font("Tahoma", 0, 12));
//    btdel.setForeground(new java.awt.Color(255, 0, 0));
    
}
