/*
 * FamilyFolder.java
 *
 * Created on 22 กันยายน 2551, 9:19 น. 
 * Updated 30 Mar 2009, 23:18.
 * Modified 20 Apr 2010 (Dulyawat) แก้ชื่อโฟลเดอร์รายงานจาก "reports" เป็น "Reports" เพื่อให้ใช้งานตรงกันทั้ง Windows และ Linux.
 */

package pcu.person;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pcu.PersistentClass.*;
import pcu.PersistentClass.Setup;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import pcu.RunReport;

public class FamilyFolder extends javax.swing.JDialog {
    DBPersistentObject db;   
    String pcucodeperson,pcucode,hcode,pid;
    String reportDir = "./Reports/FamilyFolder/";
    /** Creates new form FamilyFolder */
//    public FamilyFolder(java.awt.Frame parent, boolean modal, String _pcucodeperson, String _pid, String _hcode) {
        //public FamilyFolder(java.awt.Frame parent, boolean modal, String _pcucodeperson, String _hcode ,String _pid) {
        public FamilyFolder(java.awt.Frame parent, boolean modal, String _pcucodeperson, String _hcode ,String _pid) {
        super(parent, modal);
        this.pcucodeperson = _pcucodeperson;
        pcucode = _pcucodeperson;
        this.hcode = _hcode;
        this.pid = _pid;
        System.out.println(">>"+_pcucodeperson+"/"+_hcode+"/"+_pid);
        initComponents();
        db = new DBPersistentObject();
        ResultSet rs = db.GetResultSet("SELECT h.hno,h.hcode,v.villno,v.villname,h.road FROM house h LEFT OUTER JOIN  village v  ON h.`villcode` = v.villcode AND  h.`pcucode` = v.pcucode WHERE hcode="+hcode+" AND h.pcucode='"+pcucode+"'");
        try {
            if (rs.next()) {
                String villno = rs.getString("villno");
                String hno = rs.getString("hno");
                String hcode = rs.getString("hcode");
                String villname = rs.getString("villname");
                lbHcode.setText("บ้านเลขที่"+hno+" หมู่ที่ "+villno+" "+villname+" (ลำดับที่บ้าน "+hcode+")" );
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        if(pid != null){
        ResultSet prs = db.GetResultSet("SELECT pid,prename,fname,lname FROM person WHERE pid='"+pid+"' AND pcucodeperson='"+pcucode+"'");
        try {
            if (prs.next()) {
                String prename = prs.getString("prename");
                String fname = prs.getString("fname");
                String lname = prs.getString("lname");
                lbPerson.setText("HN : "+pid +" ชื่อ-สกุล : "+prename+fname+"  "+lname);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        }
        Setup.setFont(getContentPane().getComponents());//เมธอดที่กำหนดfonts ให้Component(ทั้งหมด...)   
        setTitle("Family Folder");
        
        //Create database connection
        db = new DBPersistentObject();          
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btHistorySick = new javax.swing.JButton();
        btVisitHomeHealthCare = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FamilyFolder_houseEnv = new javax.swing.JButton();
        btHouseMap = new javax.swing.JButton();
        btFamilyChart = new javax.swing.JButton();
        AllPersonFamilyFolder = new javax.swing.JButton();
        lbPerson = new javax.swing.JLabel();
        lbHcode = new javax.swing.JLabel();

        jButton6.setText("เยี่ยมมารดาหลังคลอด");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ข้อมูลรายบุคคล");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        btHistorySick.setText("ประวัติการเจ็บป่วย และการรับบริการอื่นๆ");
        btHistorySick.setActionCommand("familyfolder_sickhistory");
        btHistorySick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistorySickActionPerformed(evt);
            }
        });

        btVisitHomeHealthCare.setText("บันทึกการเยี่ยมบ้าน");
        btVisitHomeHealthCare.setActionCommand("FamilyFolder_HomeCare");
        btVisitHomeHealthCare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisitHomeHealthCareActionPerformed(evt);
            }
        });

        jButton8.setText("บันทึกพัฒนาการเด็ก");
        jButton8.setActionCommand("FamilyFolder_grow");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton4.setText("รายงานความพิการ");
        jButton4.setActionCommand("FamilyFolder_handycap");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("โรคเรื้อรัง");
        jButton3.setActionCommand("FamilyFolder_chronic");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton12.setText("การรับวัคซีน(เด็กและบุคคลทั่วไป)");
        jButton12.setActionCommand("FamilyFolder_epi");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton7.setText("บัตรอนามัยมารดา");
        jButton7.setActionCommand("FamilyFolder_anc");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("ประวัติการตรวจครรภ์");
        jButton9.setActionCommand("FamilyFolder_visitanc");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setText("เยี่ยมมารดาหลังคลอด");
        jButton5.setActionCommand("FamilyFolder_delivery");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("เยี่ยมทารกหลังคลอด");
        jButton1.setActionCommand("FamilyFolder_newborn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton10.setText("โภชนาการเด็ก/ชั่งน้ำหนัก");
        jButton10.setActionCommand("FamilyFolder_nutrition");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("BMI");
        jButton11.setActionCommand("FamilyFolder_bmi");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btHistorySick, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(btVisitHomeHealthCare, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(btHistorySick)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVisitHomeHealthCare)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ข้อมูลบ้านและครอบครัว");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));

        FamilyFolder_houseEnv.setText("สุขาภิบาลที่พักอาศัย");
        FamilyFolder_houseEnv.setActionCommand("FamilyFolder_houseEnv");
        FamilyFolder_houseEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamilyFolder_houseEnvActionPerformed(evt);
            }
        });

        btHouseMap.setText("แผนที่บ้าน");
        btHouseMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHouseMapActionPerformed(evt);
            }
        });

        btFamilyChart.setText("ผังเครือญาติ");
        btFamilyChart.setEnabled(false);
        btFamilyChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFamilyChartActionPerformed(evt);
            }
        });

        AllPersonFamilyFolder.setText("รายละเอียดทุกคน(รายบ้าน - ครอบครัว)");
        AllPersonFamilyFolder.setActionCommand("FamilyDetail");
        AllPersonFamilyFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllPersonFamilyFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AllPersonFamilyFolder, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btHouseMap, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FamilyFolder_houseEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btFamilyChart, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHouseMap)
                    .addComponent(FamilyFolder_houseEnv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFamilyChart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllPersonFamilyFolder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FamilyFolder_houseEnv.getAccessibleContext().setAccessibleName("FamilyFolder_houseEnv");

        lbPerson.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPerson.setText("  ");

        lbHcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHcode.setText("บ้านเลขที่ +");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHcode, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(lbPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbHcode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private void btFamilyChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFamilyChartActionPerformed
//// TODO add your handling code here:
//    String reportDir = "./Reports";
//    try {
//        Map pm = new HashMap();
//        pm.put("pcucodeperson", pcucodeperson);
//        pm.put("hcode", hcode);        
//        //pm.put("SUBREPORT_DIR", reportDir);
//        JasperPrint print = JasperFillManager.fillReport(reportDir+"/FamilyDetail.jasper", pm, db.getConnection());
//        JasperViewer.viewReport(print,false);
//        dispose();
//    } catch (JRException ex) {
//        ex.printStackTrace();
//    }    
}//GEN-LAST:event_btFamilyChartActionPerformed

private void AllPersonFamilyFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllPersonFamilyFolderActionPerformed
// TODO add your handling code here:
    print(evt);
    /*
    try {
        Map pm = new HashMap();
        pm.put("pcucodeperson", pcucodeperson);
//        pm.put("pcucode", UserInfo.pcucode);
        pm.put("hcode", hcode);        
        //pm.put("SUBREPORT_DIR", reportDir);
        JasperPrint print = JasperFillManager.fillReport(reportDir+"/FamilyDetail.jasper", pm, db.getConnection());
        JasperViewer.viewReport(print,false);
        dispose();
    } catch (JRException ex) {
        ex.printStackTrace();
    } 
     */
}//GEN-LAST:event_AllPersonFamilyFolderActionPerformed

private void btHistorySickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistorySickActionPerformed
    //if(UserInfo.pcucode == null){JOptionPane.showMessageDialog(null, "...ต้องเลือกคน(ขึ้นมาบนหน้าจอฯ) ก่อน");}
    print(evt);
}//GEN-LAST:event_btHistorySickActionPerformed

private void btHouseMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHouseMapActionPerformed
    String photoDir = "";
    String photoPath = "";
    photoDir = "/Photoes/";
    String chkFileExist = photoDir+ UserInfo.pcucode+"h"+hcode+ ".jpg";
            //CreateDeleteFileFolder cff1 = new CreateDeleteFileFolder();
     File currentDir = new File(".");
            try {
                //System.out.println(currentDir.getCanonicalPath()+chkFileExist);
                photoPath = currentDir.getCanonicalPath()+chkFileExist;
                FileInputStream in = new FileInputStream(currentDir.getCanonicalPath()+chkFileExist );
                //System.out.println(photoPath);
                //System.out.println(UserInfo.pcucode);
                //System.out.println(hcode);
                Map pm = new HashMap();
                pm.put("p_picturepath", photoPath);
                pm.put("p_pcucode", UserInfo.pcucode);
                pm.put("p_hcode", hcode);
                setVisible(false);
                new RunReport(this, pm, "FamilyFolder_housemap.jasper");

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "ไม่มีแผนที่บ้านลำดับที่ "+hcode+" อยู่ใน โฟลเดอร์ >>"+chkFileExist);
                //return;
            } catch (IOException ex) {
                 ex.printStackTrace();
            }

}//GEN-LAST:event_btHouseMapActionPerformed

private void FamilyFolder_houseEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamilyFolder_houseEnvActionPerformed
    //สุขาภิบาลที่พักอาศัย
    print(evt);
    /*
    Map pm = new HashMap();
    //pm.put("p_picturepath", chkFileExist);
    pm.put("p_officename", UserInfo.officedetail);
    pm.put("p_pcucode", UserInfo.pcucode);
    pm.put("p_hcode", hcode);
    setVisible(false);
    new RunReport(this, pm, reportDir+"FamilyFolder_houseEnv.jasper");
   */
}//GEN-LAST:event_FamilyFolder_houseEnvActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton11ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton9ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton3ActionPerformed

private void btVisitHomeHealthCareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisitHomeHealthCareActionPerformed
    print(evt);
}//GEN-LAST:event_btVisitHomeHealthCareActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton10ActionPerformed

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton12ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    print(evt);
}//GEN-LAST:event_jButton1ActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                FamilyFolder dialog = new FamilyFolder(new javax.swing.JFrame(),true,"01838","1","22");
                FamilyFolder dialog = new FamilyFolder(new javax.swing.JFrame(),true,"01838","22","1");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void print(java.awt.event.ActionEvent evt){
        Map pm = new HashMap();
        //pm.put("p_picturepath", chkFileExist);
        pm.put("p_officename", UserInfo.officedetail);
        pm.put("p_pcucode", UserInfo.pcucode);
        pm.put("p_hcode", hcode);
        pm.put("p_pid", pid);
        pm.put("pcucodeperson", pcucodeperson);
        pm.put("hcode", hcode);
        pm.put("SUBREPORT_DIR", "./Reports/FamilyFolder/");
        System.out.println("p_pcucode = "+UserInfo.pcucode);
        System.out.println("p_pid = "+pid);

        setVisible(false);
        new RunReport(this, pm, reportDir+evt.getActionCommand()+".jasper");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllPersonFamilyFolder;
    private javax.swing.JButton FamilyFolder_houseEnv;
    private javax.swing.JButton btFamilyChart;
    private javax.swing.JButton btHistorySick;
    private javax.swing.JButton btHouseMap;
    private javax.swing.JButton btVisitHomeHealthCare;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbHcode;
    private javax.swing.JLabel lbPerson;
    // End of variables declaration//GEN-END:variables

}
